spring:
  datasource:
    url: jdbc:h2:mem:medisalud;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
    open-in-view: false
  flyway:
    enabled: false
  h2:
    console:
      enabled: false

medisalud:
  nager-date:
    base-url: https://date.nager.at/api/v3
    timeout-seconds: 5

logging:
  level:
    com.medisalud.appointment: DEBUG
    org.hibernate.SQL: DEBUG
